seed: 42
do_train: True
do_predict: True
do_ED_infer: True

paradigm: token_classification

task_name: ED
dataset_name: ACE2005
output_dir: output/ACE2005
type2id_path: ../data/ace_2005_td_v7/Chinese/label2id.json
train_file: ../data/ace_2005_td_v7/Chinese/train.unified.jsonl
validation_file: ../data/ace_2005_td_v7/Chinese/valid.unified.jsonl
test_file: ../data/ace_2005_td_v7/Chinese/test.unified.jsonl
language: Chinese
test_exists_labels: True

return_token_type_ids: True
truncate_seq2seq_output: False

model_type: bert
model_name_or_path: bert-base-chinese
hidden_size: 768
aggregation: none

num_train_epochs: 10
max_seq_length: 256
max_out_length: 256
dataloader_num_workers: 2

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True
ignore_pad_token_for_loss: True

per_device_train_batch_size: 16
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
# eval_accumulation_steps: 4
learning_rate: 3.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1
greater_is_better: True

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500

