seed: 42
do_train: True
do_predict: True

paradigm: token_classification

output_dir: output
label2id: ../data/MAVEN/label2id.json 
train_file: ../data/MAVEN/train.unified.jsonl
validation_file: ../data/MAVEN/valid.unified.jsonl
test_file: ../data/MAVEN/test.unified.jsonl

model_type: roberta
model_name_or_path: roberta-base
hidden_size: 768
aggregation: dm

num_train_epochs: 5
max_seq_length: 120
dataloader_num_workers: 2

per_device_train_batch_size: 128
per_device_eval_batch_size: 128
gradient_accumulation_steps: 1
learning_rate: 3.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500


